config/routes.rb
Hatchboy::Application.routes.draw do
  #resources :docu_signs
  resources :docu_signs do
    member do
      get 'server_response'
    end
  end

  resources :docu_templates do
    get :server_response, :on => :collection
    get :autocomplete_user_name, :on => :collection
  end

  root :to => "pages#home"
  devise_for :account, :controllers => {:registrations => "registrations" }, skip: [:invitations]

  devise_scope :account do
    put   "/account/edit", :to => "registrations#update", :as => :update_account_registration
    get   "/account/invitation/accept", :to =>  "devise/invitations#edit", :as => :accept_account_invitation
    get   "/account/invitation/remove", :to =>  "devise/invitations#destroy", :as => :remove_account_invitation
    patch "/account/invitation", :to =>  "devise/invitations#update"
    put   "/account/invitation", :to =>  "devise/invitations#update", :as => :update_account_invitation
    get   "/account/invitation/new", :to =>  "invitations#new", :as => :new_user_invitation
    post  "/account/invitation/new", :to =>  "invitations#create", :as => :create_user_invitation
  end

  get "account",   :to => "accounts#show", :as => :account
  get "dashboard", :to => "dashboard#index", :as => :dashboard
  get "legal", :to => "pages#dashboard", :as => :legal

  get "billing_information", :to => "pages#billing_information", :as => :billing_information

  resources :payments do
    put "marked"
  end
  resources :paypal_configurations, :only => [:new, :create]
  resources :stripe_configurations, :only => [:new, :create]
  resources :payment_transactions, :only => [:create]
  post "payment_transactions/paypal_notify", :to => "payment_transactions#paypal_notify", :as => :paypal_notify
  post "payment_transactions/stripe_notify", :to => "payment_transactions#stripe_notify", :as => :stripe_notify

  resources :dashboard_activity_filters, :only => [:create]

  resources :reports, :controller => 'reports', only: [:index], as: :reports
  scope "/reports" do
    resources :hours, :controller => 'report_hours', only: [:index], as: :report_hours do
      collection do
        get "team/:team_id", to: "report_hours#team", as: :team
        get "user/:user_id", to: "report_hours#user", as: :user
      end
    end
    resources :payments, :controller => 'report_payments', only: [:index], as: :report_payments do
      get "user/:user_id", to: "report_payments#user", as: :user, on: :collection
    end
    resources :ratings, :controller => 'report_ratings', only: [:index], as: :report_ratings do
      get "user/:user_id", to: "report_ratings#user", as: :user, on: :collection
    end
    resources :mvp, :controller => 'report_mvp', only: [:index], as: :report_mvp do
      get "user/:user_id", to: "report_mvp#user", as: :user, on: :collection
    end
  end
  resources :user_multi_ratings, :only => [:create]

  get "messages", :to => "pages#dashboard", :as => :messages

  get "mail/", :to => "pages#mail", :as => :account_mail
  get "mail/:folder", :to => "pages#mail", :as => :account_mail_folder
  get "compose", :to => "pages#compose", :as => :compose_mail

  get "company",   :to => "companies#show"
  get "company/edit", :to => "companies#edit", :as => :edit_company
  put "company",   :to => "companies#update"
  patch "company", :to => "companies#update"

  resources :users do
    resource :teams, :to => "teams_users", only: [:destroy] do
      get "new", to: "teams_users#new_team", as: "new", on: :collection
      post "create", to: "teams_users#create_team", as: "create", on: :collection
    end
    resource :stripe_recipient
  end

  resources :subscriptions, only: [:edit, :update]
  delete "/unsubscribed_teams/:id", to: "unsubscribed_teams#subscribe", as: :unsubscribed_team
  get "/subscriptions/unsubscribe", to: "subscriptions#unsubscribe"
  get "/team/:team_id/unsubscribe", to: "unsubscribed_teams#unsubscribe", as: :unsubscribed_teams_unsubscribe

  resources :sources, only: [:index, :new]

  get "jira_sources/callback", :to => "jira_sources#callback", :as => :jira_callback

  resources :jira_sources do
    get "generate_public_cert", :to => "jira_sources", on: :collection
    get "confirm", :to => "jira_sources", :as => :confirm
    get "browse", :to => "jira_sources", :as => :browse
    put "sync", :to => "jira_sources", :as => :sync
  end

  get "trello_sources/callback", :to => "trello_sources#callback", :as => :trello_callback

  resources :trello_sources do
    get "confirm", :to => "trello_sources", :as => :confirm
    get "browse", :to => "trello_sources", :as => :browse
    put "sync", :to => "trello_sources", :as => :sync
  end

  resources :help_links

  get "/tutorials", to: "help_links#tutorials", as: :tutorials

  resources :posts

  resources :teams do
    resources :work_logs, except: [:view]
    resources :sources, :to => "teams_sources"
    resources :jira_sources, :to => "teams_jira_sources"
    resources :users, :to => "teams_users", only: [:destroy] do
      get "new", :to => "teams_users#new_user", as: "new", on: :collection
      post "create", :to => "teams_users#create_user", as: "create", on: :collection
    end
  end
end

app/controllers/report_ratings_controller.rb
class ReportRatingsController < ApplicationController
  
  before_filter :check_session!

  include ReportsHelper

  def user
    @user = account_company.users.find(params[:user_id]) or not_found
    @current_user_scores = current_account.user.user_multi_ratings.current_period.where(rated: @user).all.group_by(&:aspect_code)
    @aspect_scores = @user.multi_ratings_by_users.current_period.group(:aspect_code).select('aspect_code, avg(score) AS aspect_score')
    scores = UserAvgRating.where(rated: @user).group(:date_period).order(:date_period).select('date_period, avg(avg_score) AS rating')
    if scores.length > 1
      @chart = LazyHighCharts::HighChart.new('graph') do |f|
        f.title({ :text=>"360* ratings of #{@user.name}"})
        f.options[:xAxis][:categories] = scores.collect{|s| s.date_period.strftime("%B %Y")}
        f.options[:chart][:zoomType] = 'x,y'
        f.series(:type=> 'spline',:name=> 'Rating', :data=> scores.map(&:rating).collect{|score| score.round(2)})
        f.yAxis [{:title => {:text => "Rating value", :margin => 10}, :min => 0, :max => UserMultiRating::MAX_RATING},]
      end
    end
  end
end

app/views/report_ratings/_report.html.haml
- if @ratings_report.chart
  .row
    = high_chart("ratings_chart", @ratings_report.chart)

.row
  .action-list.grid.simple
    .grid-title.no-border
      %h4
        %span.semi-bold Users
      .tools
        %a.collapse{:href => "javascript:;"}
    .grid-body.no-border
      = render partial: "report_ratings/users_list"

app/views/report_ratings/_user_rating.html.haml
- USER_MULTI_RATING_ASPECTS.each do |code, aspect|
  - score = @aspect_scores.select{|s| s.aspect_code == code}.first
  - aspect_score = score ? score.aspect_score : 0
  .row{data: {aspect_code: code}}
    .col-md-8
      = aspect
    .col-md-3
      .progress
        .progress-bar.progress-bar-success{style: "width: #{val_in_percent(aspect_score, UserMultiRating::MAX_RATING)}%", role: "progressbar-bar", data: {percentage: "#{val_in_percent(aspect_score, UserMultiRating::MAX_RATING)}%"}}
    .col-md-1.total_score
      = "#{aspect_score.round(2)} / #{UserMultiRating::MAX_RATING}"

app/views/report_ratings/_user_rating_form.html.haml
= form_for(current_account.user.user_multi_ratings.build(rated_id: @user.id), url: user_multi_ratings_path, remote: true) do |f|
  = f.hidden_field :rated_id
  = f.hidden_field :rater_id
  %table.table.table-hover.table-condensed.dataTable
    %thead
      %tr
        %th{width: "#{100 - UserMultiRating::MAX_RATING}%"} Aspect
        - (1..UserMultiRating::MAX_RATING).each do |score|
          %th{width: "1%"}= score
    
      %tbody
        - USER_MULTI_RATING_ASPECTS.each do |code, aspect|
          %tr
            %td= aspect
            - (1..UserMultiRating::MAX_RATING).each do |score|
              %td
                .radio.radio-success
                  = radio_button_tag "user_multi_rating[score][#{code}]", score, (@current_user_scores[code] and @current_user_scores[code].first.score == score), disabled: !@current_user_scores[code].nil?
                  = label_tag "user_multi_rating_score_#{code}_#{score}", "&nbsp;".html_safe
  
  - if @current_user_scores.count == USER_MULTI_RATING_ASPECTS.count
    = link_to "Back", reports_path(:type => "ratings"), :class => "btn btn-white btn-cons"
  - else
    = f.submit "Rate", class: "btn btn-primary btn-cons rate-btn"
    = link_to "Back", reports_path(:type => "ratings"), :class => "btn btn-white btn-cons cansel-btn", :style => "display: #{@current_user_scores.count > 0 ? 'inline-block' : 'none'}"

app/views/report_ratings/_users_list.html.haml
%table.table.table-hover.table-striped.table-bordered.no-more-tables.action-list#users-short-list
  %thead
    %tr
      %th{:width => "60%"} Name
      %th{:width => "30%"} Rating
      %th{:width => "10%"}
  %tbody
    = render partial: "report_ratings/users_list_row", collection: @ratings_report.users

app/views/report_ratings/_users_list_row.html.haml
%tr.data-row
  %td= users_list_row.name
  %td= users_list_row.rating.to_f
  %td
    - if current_account.user != users_list_row and current_account.user.can_rate? users_list_row
      = link_to "Rate", user_report_ratings_path(users_list_row), :class => "btn btn-primary btn-sm btn-small"
    - else
      = link_to "View", user_report_ratings_path(users_list_row), :class => "btn btn-warning btn-sm btn-small"

app/views/report_ratings/user.html.haml
%ul.breadcrumb
  %li
    %p
      YOU ARE HERE
  %i.icon-angle-right
  %li
    %a{:href => company_path} Company
  %i.icon-angle-right
  %li
    %a{:href => reports_path(:type => "ratings")} Performance Analyzes
  %i.icon-angle-right
  %li
    %a.active{:href => user_report_ratings_path(@user)} User

.row
  .col-md-11
    .page-title
      %i.icon-custom-ui
      %h3= @user.name
  .col-md-1.text-right

- if @chart
  .row
    = high_chart("main_chart", @chart)
    
.row
  .action-list.grid.simple
    .grid-title.no-border
      %h4
        %span.semi-bold
          Current rating - 
          %span#user-current-rating= @user.rating.to_f
          \/
          %span= UserMultiRating::MAX_RATING

      .tools
        %a.collapse{:href => "javascript:;"}
    .grid-body.no-border#user_ratings
      = render 'report_ratings/user_rating'

- if current_account.user != @user
  .row
    .action-list.grid.simple
      .grid-title.no-border
        %h4
          %span.semi-bold Rating form
        .tools
          %a.collapse{:href => "javascript:;"}
      .grid-body.no-border
        = render 'report_ratings/user_rating_form'