config/routes.rb
Hatchboy::Application.routes.draw do
  #resources :docu_signs
  resources :docu_signs do
    member do
      get 'server_response'
    end
  end

  resources :docu_templates do
    get :server_response, :on => :collection
    get :autocomplete_user_name, :on => :collection
  end

  root :to => "pages#home"
  devise_for :account, :controllers => {:registrations => "registrations" }, skip: [:invitations]

  devise_scope :account do
    put   "/account/edit", :to => "registrations#update", :as => :update_account_registration
    get   "/account/invitation/accept", :to =>  "devise/invitations#edit", :as => :accept_account_invitation
    get   "/account/invitation/remove", :to =>  "devise/invitations#destroy", :as => :remove_account_invitation
    patch "/account/invitation", :to =>  "devise/invitations#update"
    put   "/account/invitation", :to =>  "devise/invitations#update", :as => :update_account_invitation
    get   "/account/invitation/new", :to =>  "invitations#new", :as => :new_user_invitation
    post  "/account/invitation/new", :to =>  "invitations#create", :as => :create_user_invitation
  end

  get "account",   :to => "accounts#show", :as => :account
  get "dashboard", :to => "dashboard#index", :as => :dashboard
  get "legal", :to => "pages#dashboard", :as => :legal

  get "billing_information", :to => "pages#billing_information", :as => :billing_information

  resources :payments do
    put "marked"
  end
  resources :paypal_configurations, :only => [:new, :create]
  resources :stripe_configurations, :only => [:new, :create]
  resources :payment_transactions, :only => [:create]
  post "payment_transactions/paypal_notify", :to => "payment_transactions#paypal_notify", :as => :paypal_notify
  post "payment_transactions/stripe_notify", :to => "payment_transactions#stripe_notify", :as => :stripe_notify

  resources :dashboard_activity_filters, :only => [:create]

  resources :reports, :controller => 'reports', only: [:index], as: :reports
  scope "/reports" do
    resources :hours, :controller => 'report_hours', only: [:index], as: :report_hours do
      collection do
        get "team/:team_id", to: "report_hours#team", as: :team
        get "user/:user_id", to: "report_hours#user", as: :user
      end
    end
    resources :payments, :controller => 'report_payments', only: [:index], as: :report_payments do
      get "user/:user_id", to: "report_payments#user", as: :user, on: :collection
    end
    resources :ratings, :controller => 'report_ratings', only: [:index], as: :report_ratings do
      get "user/:user_id", to: "report_ratings#user", as: :user, on: :collection
    end
    resources :mvp, :controller => 'report_mvp', only: [:index], as: :report_mvp do
      get "user/:user_id", to: "report_mvp#user", as: :user, on: :collection
    end
  end
  resources :user_multi_ratings, :only => [:create]

  get "messages", :to => "pages#dashboard", :as => :messages

  get "mail/", :to => "pages#mail", :as => :account_mail
  get "mail/:folder", :to => "pages#mail", :as => :account_mail_folder
  get "compose", :to => "pages#compose", :as => :compose_mail

  get "company",   :to => "companies#show"
  get "company/edit", :to => "companies#edit", :as => :edit_company
  put "company",   :to => "companies#update"
  patch "company", :to => "companies#update"

  resources :users do
    resource :teams, :to => "teams_users", only: [:destroy] do
      get "new", to: "teams_users#new_team", as: "new", on: :collection
      post "create", to: "teams_users#create_team", as: "create", on: :collection
    end
    resource :stripe_recipient
  end

  resources :subscriptions, only: [:edit, :update]
  delete "/unsubscribed_teams/:id", to: "unsubscribed_teams#subscribe", as: :unsubscribed_team
  get "/subscriptions/unsubscribe", to: "subscriptions#unsubscribe"
  get "/team/:team_id/unsubscribe", to: "unsubscribed_teams#unsubscribe", as: :unsubscribed_teams_unsubscribe

  resources :sources, only: [:index, :new]

  get "jira_sources/callback", :to => "jira_sources#callback", :as => :jira_callback

  resources :jira_sources do
    get "generate_public_cert", :to => "jira_sources", on: :collection
    get "confirm", :to => "jira_sources", :as => :confirm
    get "browse", :to => "jira_sources", :as => :browse
    put "sync", :to => "jira_sources", :as => :sync
  end

  get "trello_sources/callback", :to => "trello_sources#callback", :as => :trello_callback

  resources :trello_sources do
    get "confirm", :to => "trello_sources", :as => :confirm
    get "browse", :to => "trello_sources", :as => :browse
    put "sync", :to => "trello_sources", :as => :sync
  end

  resources :help_links

  get "/tutorials", to: "help_links#tutorials", as: :tutorials

  resources :posts

  resources :teams do
    resources :work_logs, except: [:view]
    resources :sources, :to => "teams_sources"
    resources :jira_sources, :to => "teams_jira_sources"
    resources :users, :to => "teams_users", only: [:destroy] do
      get "new", :to => "teams_users#new_user", as: "new", on: :collection
      post "create", :to => "teams_users#create_user", as: "create", on: :collection
    end
  end
end

app/controllers/report_payments_controller.rb
class ReportPaymentsController < ApplicationController
  
  before_filter :check_session!

  include ReportsHelper

  def user
    @user = account_company.users.where(id: params[:user_id]).first or not_found
    query_params = retrieve_query_params :payments, [:date, :specific_date, :period_from, :period_to]
    user_payments = Hatchboy::Reports::Filters::PaymentsFilter.new(PaymentRecipient.where(user_id: @user.id).select(:payment_id).group(:payment_id)).with_statuses([Payment::STATUS_SENT, Payment::STATUS_MARKED]).filter_by_params(query_params).to_a
    
    @payments = user_payments.map(&:payment).uniq
    @payments_amounts = user_payments.group_by(&:payment_id)

    chart_data = group_timeline_from_params user_payments, query_params do |scope, date|
      @payments.collect do |payment|
        payment_rec = scope.select{|p| payment.id == p.payment_id}.first if scope
        { id: payment.id, name: "Payment \##{payment.id} - #{payment.created_by.name}", value: payment_rec ? payment_rec.amount.round(2) : 0}
      end
    end
    
    @chart = build_chart({title: "Payments sent to #{@user.name} for #{report_title_from_params(query_params)}", y_title: "$", data: chart_data})
  end
end

app/views/report_payments/_filter.html.haml
=hidden_field_tag :set_filter, 1
=hidden_field_tag :type, :payments

= render partial: "reports/date_filter", locals: {params: params}

.col-md4.pull-right
  = submit_tag "Apply", class: "btn btn-primary btn-cons", name: ""

app/views/report_payments/_report.html.haml
- if @payments_report.chart
  .row
    = high_chart("payments_chart", @payments_report.chart)

.row
  .action-list.grid.simple
    .grid-title.no-border
      %h4
        %span.semi-bold Users payments
      .tools
        %a.collapse{:href => "javascript:;"}
    .grid-body.no-border
      = form_tag(reports_path, method: "get", id: "report-payments-filter-form") do
        #report-filter-block.row{style: "margin-bottom: 20px;"}
          = render partial: "report_payments/filter", locals: {params: @payments_report.params}
        #report-data-block.row
          = render partial: "report_payments/users_report_table", locals: {params: @payments_report.params}

:coffeescript
  $ ->
    $.payments_report = $.extend({}, $.reports)
    $.payments_report.init(
      with_date_filter: true,
      selectors:
        form: "#report-payments-filter-form"
    )

app/views/report_payments/_user_payments_list_row.html.haml
%tr.data-row
  %td= user_payments_list_row.created_by.name
  %td= @payments_amounts[user_payments_list_row.id].map(&:amount).reduce(:+)

app/views/report_payments/_users_list_row.html.haml
%tr.data-row
  %td
    .checkbox
      %input.check{:id => "payments-users-#{users_list_row.id}", type: 'checkbox', value: users_list_row.id, name: 'users[]', checked: (params[:users] and params[:users].include? users_list_row.id.to_s)}
      %label{:for => "payments-users-#{users_list_row.id}"}
  %td=link_to users_list_row.name, user_report_payments_path( users_list_row )
  %td= @payments_report.users_payments[users_list_row.id].map(&:amount).reduce(:+)

app/views/report_payments/_users_report_table.html.haml
%table.table.table-hover.table-striped.table-bordered.no-more-tables.action-list#users-report-payments-list
  %thead
    %tr
      %th{:width => "2%"}
        .checkbox
          %input.checkall#checkall-payments-users{type: 'checkbox', value: 1  }
          %label{for: 'checkall-payments-users'}
      %th{:width => "49%"} User Name
      %th{:width => "49%"} Total amount
  %tbody
    - if @payments_report.users and @payments_report.users.count > 0
      = render partial: "report_payments/users_list_row", collection: @payments_report.users, locals: {params: @payments_report.params}
    - else 
      %tr.text-center
        %td{:colspan => "3"}
          No data to display

app/views/report_payments/user.html.haml
%ul.breadcrumb
  %li
    %p
      YOU ARE HERE
  %i.icon-angle-right
  %li
    %a{:href => company_path} Company
  %i.icon-angle-right
  %li
    %a{:href => reports_path(:type => "payments")} Performance Analyzes
  %i.icon-angle-right
  %li
    %a.active{:href => user_report_hours_path(@user)} User

.row
  .col-md-11
    .page-title
      %i.icon-custom-ui
      %h3= @user.name
  .col-md-1.text-right

- if @chart
  .row
    = high_chart("main_chart", @chart)
    
.row
  .action-list.grid.simple
    .grid-title.no-border
      %h4
        %span.semi-bold
        = @user.name
      .tools
        %a.collapse{:href => "javascript:;"}
    .grid-body.no-border
      .row
        %table.table.table-hover.table-striped.table-bordered.no-more-tables.action-list#teams-short-list
          %thead
            %tr
              %th{:width => "50%"} Created by
              %th{:width => "50%"} Amount
          %tbody
            = render partial: "report_payments/user_payments_list_row", collection: @payments