config/routes.rb
Hatchboy::Application.routes.draw do
  #resources :docu_signs
  resources :docu_signs do
    member do
      get 'server_response'
    end
  end

  resources :docu_templates do
    get :server_response, :on => :collection
    get :autocomplete_user_name, :on => :collection
  end

  root :to => "pages#home"
  devise_for :account, :controllers => {:registrations => "registrations" }, skip: [:invitations]

  devise_scope :account do
    put   "/account/edit", :to => "registrations#update", :as => :update_account_registration
    get   "/account/invitation/accept", :to =>  "devise/invitations#edit", :as => :accept_account_invitation
    get   "/account/invitation/remove", :to =>  "devise/invitations#destroy", :as => :remove_account_invitation
    patch "/account/invitation", :to =>  "devise/invitations#update"
    put   "/account/invitation", :to =>  "devise/invitations#update", :as => :update_account_invitation
    get   "/account/invitation/new", :to =>  "invitations#new", :as => :new_user_invitation
    post  "/account/invitation/new", :to =>  "invitations#create", :as => :create_user_invitation
  end

  get "account",   :to => "accounts#show", :as => :account
  get "dashboard", :to => "dashboard#index", :as => :dashboard
  get "legal", :to => "pages#dashboard", :as => :legal

  get "billing_information", :to => "pages#billing_information", :as => :billing_information

  resources :payments do
    put "marked"
  end
  resources :paypal_configurations, :only => [:new, :create]
  resources :stripe_configurations, :only => [:new, :create]
  resources :payment_transactions, :only => [:create]
  post "payment_transactions/paypal_notify", :to => "payment_transactions#paypal_notify", :as => :paypal_notify
  post "payment_transactions/stripe_notify", :to => "payment_transactions#stripe_notify", :as => :stripe_notify

  resources :dashboard_activity_filters, :only => [:create]

  resources :reports, :controller => 'reports', only: [:index], as: :reports
  scope "/reports" do
    resources :hours, :controller => 'report_hours', only: [:index], as: :report_hours do
      collection do
        get "team/:team_id", to: "report_hours#team", as: :team
        get "user/:user_id", to: "report_hours#user", as: :user
      end
    end
    resources :payments, :controller => 'report_payments', only: [:index], as: :report_payments do
      get "user/:user_id", to: "report_payments#user", as: :user, on: :collection
    end
    resources :ratings, :controller => 'report_ratings', only: [:index], as: :report_ratings do
      get "user/:user_id", to: "report_ratings#user", as: :user, on: :collection
    end
    resources :mvp, :controller => 'report_mvp', only: [:index], as: :report_mvp do
      get "user/:user_id", to: "report_mvp#user", as: :user, on: :collection
    end
  end
  resources :user_multi_ratings, :only => [:create]

  get "messages", :to => "pages#dashboard", :as => :messages

  get "mail/", :to => "pages#mail", :as => :account_mail
  get "mail/:folder", :to => "pages#mail", :as => :account_mail_folder
  get "compose", :to => "pages#compose", :as => :compose_mail

  get "company",   :to => "companies#show"
  get "company/edit", :to => "companies#edit", :as => :edit_company
  put "company",   :to => "companies#update"
  patch "company", :to => "companies#update"

  resources :users do
    resource :teams, :to => "teams_users", only: [:destroy] do
      get "new", to: "teams_users#new_team", as: "new", on: :collection
      post "create", to: "teams_users#create_team", as: "create", on: :collection
    end
    resource :stripe_recipient
  end

  resources :subscriptions, only: [:edit, :update]
  delete "/unsubscribed_teams/:id", to: "unsubscribed_teams#subscribe", as: :unsubscribed_team
  get "/subscriptions/unsubscribe", to: "subscriptions#unsubscribe"
  get "/team/:team_id/unsubscribe", to: "unsubscribed_teams#unsubscribe", as: :unsubscribed_teams_unsubscribe

  resources :sources, only: [:index, :new]

  get "jira_sources/callback", :to => "jira_sources#callback", :as => :jira_callback

  resources :jira_sources do
    get "generate_public_cert", :to => "jira_sources", on: :collection
    get "confirm", :to => "jira_sources", :as => :confirm
    get "browse", :to => "jira_sources", :as => :browse
    put "sync", :to => "jira_sources", :as => :sync
  end

  get "trello_sources/callback", :to => "trello_sources#callback", :as => :trello_callback

  resources :trello_sources do
    get "confirm", :to => "trello_sources", :as => :confirm
    get "browse", :to => "trello_sources", :as => :browse
    put "sync", :to => "trello_sources", :as => :sync
  end

  resources :help_links

  get "/tutorials", to: "help_links#tutorials", as: :tutorials

  resources :posts

  resources :teams do
    resources :work_logs, except: [:view]
    resources :sources, :to => "teams_sources"
    resources :jira_sources, :to => "teams_jira_sources"
    resources :users, :to => "teams_users", only: [:destroy] do
      get "new", :to => "teams_users#new_user", as: "new", on: :collection
      post "create", :to => "teams_users#create_user", as: "create", on: :collection
    end
  end
end

app/models/docu_sign.rb
class DocuSign < ActiveRecord::Base
  include PublicActivity::Model
  tracked only: :update, 
          on: { :update => proc do |docu_sign, controller| 
            docu_sign.status == STATUS_SIGNED and docu_sign.status_changed?
          end },
          owner: ->(controller, model) { controller && controller.current_user },
          company_id: ->(controller, docu_sign) { docu_sign.company_id }

  belongs_to :user
  belongs_to :docu_template
  belongs_to :company
  
  STATUS_PROCESSING = "processing"
  STATUS_SIGNED = "signed"
  STATUS_CANCELLED = "cancelled"
  
  before_validation :get_envelope

  private
  
  def get_envelope
    client = DocusignRest::Client.new

    response = client.create_envelope_from_template(
      status: 'sent',
      email: {
        subject: "The test email subject envelope",
        body: "Envelope body content here"
      },
      template_id: self.docu_template.template_key,
      signers: [
        {
          embedded: true,
          name: self.user.name,
          email: self.user.account.email,
          role_name: 'Signer'
        }
      ]
    )

    self.status = DocuSign::STATUS_PROCESSING
    self.errors.add(:users, response["message"] ) unless self.envelope_key = response["envelopeId"]
  end

end

app/controllers/docu_signs_controller.rb
class DocuSignsController < ApplicationController

  before_action :set_docu_sign, only: [:server_response, :show, :edit, :update, :destroy]
  before_filter :authenticate_account!
  
  after_action :allow_docusign_iframe , only: :show

  def autocomplete_user_name
    users = account_company.users.where( ["name LIKE ?", "%#{params[:q]}%" ] )
    users = users.map { |a| { :id => "user_#{a.id}", :text => a.name, :type => "user" } }
    
    teams = account_company.teams.where( ["name LIKE ?", "%#{params[:q]}%" ] )
    teams = teams.map { |a| { :id => "team_#{a.id}", :text => a.name, :type => "team" } }

    render :json => users.inject(teams, :<<)
  end

  # GET /docu_signs
  # GET /docu_signs.json
  def index
    @docu_signs = DocuSign.where(:user => current_account.user)
    @docs_to_sign = @docu_signs.select{|doc| doc.status == DocuSign::STATUS_PROCESSING }.count
  end

  # GET /docu_signs/1
  # GET /docu_signs/1.json
  def show
    client = DocusignRest::Client.new

    @url = client.get_recipient_view(
      envelope_id: @docu_sign.envelope_key,
      name: @docu_sign.user.name,
      email: @docu_sign.user.account.email,
      return_url: url_for(  action: 'server_response',only_path: false )
    )

  end

  # GET /docu_signs/new
  def new
    @docu_template = DocuTemplate.new
  end

  # GET /docu_signs/1/edit
  def edit
  end

  # POST /docu_signs
  # POST /docu_signs.json
  def create
    @docu_template = DocuTemplate.new(docu_sign_params)
    @docu_template.company = account_company
    @docu_template.user = current_account.user

    respond_to do |format|
      if @docu_template.save
        format.html { redirect_to docu_signs_path, notice: 'Docu sign was successfully created.' }
        format.json { render action: 'show', status: :created, location: @docu_sign }
      else

        puts @docu_template.errors.to_yaml
        format.html { render action: 'new' }
        format.json { render json: @docu_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docu_signs/1
  # PATCH/PUT /docu_signs/1.json
  def update
    respond_to do |format|
      if @docu_sign.update(docu_sign_params)
        format.html { redirect_to @docu_sign, notice: 'Docu sign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @docu_sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docu_signs/1
  # DELETE /docu_signs/1.json
  def destroy
    @docu_sign.destroy
    respond_to do |format|
      format.html { redirect_to docu_signs_url }
      format.json { head :no_content }
    end
  end

  def server_response
    utility = DocusignRest::Utility.new

    if params[:event] == "signing_complete"
      client = DocusignRest::Client.new
      recipients = client.get_envelope_recipients(
        envelope_id: @docu_sign.envelope_key,
        include_tabs: true,
        include_extended: true
      )

      rcheck = recipients["signers"][0]

      if rcheck["status"]=="completed" and rcheck["name"]==current_account.user.name and rcheck["email"]==current_account.email
        @docu_sign.update_attribute(:status, DocuSign::STATUS_SIGNED)
      end
      flash[:notice] = "Thanks! Successfully signed"
      render :text => utility.breakout_path(docu_templates_url), content_type: 'text/html'
    elsif params[:event] == "decline"
      flash[:notice] = "You chose not to sign the document."
      @docu_sign.update_attribute(:status, DocuSign::STATUS_CANCELLED)
      render :text => utility.breakout_path(docu_templates_url), content_type: 'text/html'
    else
      flash[:notice] = "You chose to cancel signing process."
      render :text => utility.breakout_path(docu_templates_url), content_type: 'text/html'
    end

    store_docs_to_sign
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docu_sign
      @docu_sign = DocuSign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docu_sign_params
      params.require(:docu_template).permit(:users, :document, :title)
    end

    def allow_docusign_iframe
      response.headers.except! 'X-Frame-Options'
    end    
end

app/helpers/docu_signs_helper.rb
module DocuSignsHelper
end

app/views/docu_signs/_form.html.haml
= simple_form_for(form, :url => docu_templates_path, :html => { :multipart => true }, :remote => true) do |f|
  .grid-title.no-border
    = display_flash_message :error, f.error_notification
  .grid-body.no-border
    .row
      .col-md-6
        %br/
        .form-group
          %label.form-label Title
          %span.help e.g. "Tax form"
          .controls
            = f.input_field :title
        .form-group
          %label.form-label Document
          %span.help click to upload
          .controls
            = f.input_field :document, as: :file, accept: 'application/pdf'
      .col-md-6
        %br/
        .form-group
          %label.form-label Send to users or teams
          %span.help click to add 
          .controls
            = f.simple_fields_for :docu_signs do |docu|
              = docu.input_field :users, input_html: {type: "hidden", id:"e6", style:"width:600px" }
        .row-fluid
          %br/
          %br/
          .checkbox.check-success
            %input#docu_template_self_sign{:checked => false, :type => "checkbox", :value => "0", :name => "docu_template[self_sign]"}
              %label{:for => "docu_template_self_sign"} Sign uploaded document
            %button.btn.btn-success.btn-cons{:type => "submit"}
              %i.icon-ok
              Send
            = link_to "Cancel", docu_templates_path, :class => "btn btn-white btn-cons"

app/views/docu_signs/autocomplete_user_name.js.haml
- for user in @users
  = user.name
  ,
  = user.name
  |
  = user.id

app/views/docu_signs/create.js.haml
- if @docu_template.errors.count == 0
  $('#new_form').html('#{j render :partial => "form", :object => DocuTemplate.new}');
- else
  $('#new_form').html('#{j render :partial => "form", :object => @docu_template}');
  

- if  session[:docusign] and session[:docusign][:status] == "created"
  console.log("session docusign")
  var iframe = document.createElement('iframe');
  // iframe.style.display = "none";
  iframe.src = "#{ @recipient_view["url"] }";
  iframe.style = "width:1500px;height:1000px"
  $("#docusign_iframe").show();
  $("#docusign_iframe").append(iframe);

  

-#
  alert('success!');
  - if remotipart_submitted?
    alert('submitted via remotipart')
  - else
    alert('submitted via native jquery-ujs')

app/views/docu_signs/edit.html.haml
%h1 Editing docu_sign

= render 'form'

= link_to 'Show', @docu_sign
\|
= link_to 'Back', docu_signs_path

app/views/docu_signs/index.html.haml
%ul.breadcrumb
  %li
    %p YOU ARE HERE
  %i.icon-angle-right
  %li
    %a.active{:href => "#"} Tables
.page-title
  %i.icon-custom-left
  %h3
    Advance -
    %span.semi-bold Tables

.row
  %ul#navigation-tab.nav.nav-tabs
    %li.active
      %a{:href => "#users-tab"} My documents
    %li
      %a{:href => "#work-logs-tab"} Company's documents
  .tab-content
    #users-tab.tab-pane.active
      =#render partial: "users/team_users", :object => @team.users, locals: { team: @team }
      .row-fluid
        .span12
          .grid.simple
            .grid-title
              %h4
                Advance
                %span.semi-bold
                  Options
              .tools
                %a.collapse{:href => "javascript:;"}
                %a.config{"data-toggle" => "modal", :href => "#grid-config"}
                %a.reload{:href => "javascript:;"}
                %a.remove{:href => "javascript:;"}
            .grid-body
              .toolbar
                .table-tools-actions
              %table#example3.table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                %thead
                  %tr
                    %th Title
                    %th User
                    %th Status
                    %th Action
                %tbody
                  - @docu_signs.each do |docu_sign|
                    %tr
                      %td= docu_sign.docu_template.title
                      %td= docu_sign.user.name
                      %td= docu_sign.status
                      %td
                        = link_to 'Show', docu_sign
                        = #link_to 'Edit', edit_docu_sign_path(docu_sign)
                        = link_to 'Destroy', docu_sign, :method => :delete, :data => { :confirm => 'Are you sure?' }
    #work-logs-tab.tab-pane
      =#render partial: "work_logs/team_work_logs", :object => @team.worklogs, locals: { team: @team }
      .row-fluid
        .span12
          .grid.simple
            .grid-title
              %h4
                Advance
                %span.semi-bold
                  Options
              .tools
                %a.collapse{:href => "javascript:;"}
                %a.config{"data-toggle" => "modal", :href => "#grid-config"}
                %a.reload{:href => "javascript:;"}
                %a.remove{:href => "javascript:;"}
            .grid-body
              .toolbar
                .table-tools-actions
                  %button#test2.btn.btn-primary{:style => "margin-left:12px"}
                    = link_to 'Add', new_docu_template_path
              %table#example3.table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
                %thead
                  %tr
                    %th Title
                    %th User
                    %th Status
                    %th Action
                %tbody
                  - @docu_signs.each do |docu_sign|
                    %tr
                      %td= docu_sign.docu_template.title
                      %td= docu_sign.user.name
                      %td= docu_sign.status
                      %td
                        = link_to 'Show', docu_sign
                        = #link_to 'Edit', edit_docu_sign_path(docu_sign)
                        = link_to 'Destroy', docu_sign, :method => :delete, :data => { :confirm => 'Are you sure?' }

=content_for :javascript do
  =javascript_include_tag "js/tabs_accordian"

app/views/docu_signs/new.html.haml
-#
  %ul.breadcrumb
    %li
      %p
        YOU ARE HERE
    %i.icon-angle-right
    %li
      %a{:href => docu_signs_path}< Documents
    %i.icon-angle-right
    %li
      %a.active{:href => docu_signs_path} New  
  .row
    .col-md-12    
      .page-title
        %i.icon-custom-ui
        %h3 Add Document
  .row
    .col-md-12
      .grid.simple
        .grid-title.no-border
          %h4
            %span.semi-bold 
              Document for
              = account_company.name
              company
          .tools
        .grid-body.no-border
          = render 'form'

%ul.breadcrumb
  %li
    %p
      YOU ARE HERE
  %i.icon-angle-right
  %li
    %a{:href => docu_signs_path}< Documents
  %i.icon-angle-right
  %li
    %a.active{:href => docu_signs_path} New  
.row
  .col-md-12    
    .page-title
      %i.icon-custom-ui
      %h3 Add Document
.row
  .col-md-12
    .grid.simple
      .grid-title.no-border
        %h4
          %span.semi-bold 
            Add Document for
            = account_company.name
            company
        .tools
        #new_form
          =render partial: "docu_templates/form", :object => @docu_template
      #docusign_iframe.grid-body.no-border
        %h3
          Uploaded document
%iframe{:src => "https://demo.docusign.net/Member/StartInSession.aspx?t=cfdf6c34-6ecb-4b1c-ba4e-af4366cb1330&cache=#{Time.now.to_i}", :style => "width:1500px;height:1000px"}



:javascript
  
  var docusign_complete = function () {
    alert("docusign_completed");
    console.log("docusign_completed");
  };

  var docusign_cancelled = function () {
    alert("docusign_cancelled");
    console.log("docusign_cancelled");
  };

-#
  = simple_form_for(@docu_template, :url => docu_templates_path, :html => { :multipart => true }, :remote => true) do |f|
    .grid-title.no-border
      = display_flash_message :error, f.error_notification
    .grid-body.no-border
      .row
        .col-md-6
          %br/
          .form-group
            %label.form-label Title
            %span.help e.g. "Tax form"
            .controls
              = f.input_field :title
          .form-group
            %label.form-label Document
            %span.help click to upload
            .controls
              = f.input_field :document, as: :file, accept: 'application/pdf'
        .col-md-6
          %br/
          .form-group
            %label.form-label Send to users or teams
            %span.help click to add 
            .controls
              = f.simple_fields_for :docu_signs do |docu|
                = docu.input_field :users, input_html: {type: "hidden", id:"e6", style:"width:600px" }
          .row-fluid
            %br/
            %br/
            .checkbox.check-success
              %input#docu_template_self_sign{:checked => false, :type => "checkbox", :value => "0", :name => "docu_template[self_sign]"}
                %label{:for => "docu_template_self_sign"} Sign uploaded document
              %button.btn.btn-success.btn-cons{:type => "submit"}
                %i.icon-ok
                Send
              = link_to "Cancel", docu_templates_path, :class => "btn btn-white btn-cons"

app/views/docu_signs/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @docu_sign.status

= link_to 'Back', docu_templates_path

%iframe{:src => @url["url"], :style => "width:1500px;height:1000px"}
  %p DocuSign iFrame